
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class AddAppoint extends javax.swing.JFrame {
static String x;
    /**
     * Creates new form AddAppoint
     */
    public AddAppoint() {
        initComponents();
        jComboBox5.removeAll();
        try{
            Class.forName("com.mysql.jdbc.Driver");
        
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/telemedicine", "root", "");
          Statement st = con.createStatement();
          String qry="select pid from lpatients;";
      ResultSet rs= st.executeQuery(qry);
      jComboBox1.removeAll();
      while(rs.next()){
          
      jComboBox1.addItem(rs.getString(1));
      }
      rs.close();
      st.close();
         
        
        }
        catch(Exception e){
        System.out.println(e);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(210, 40, 140, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Allergist", "Anesthesiologist", "Cardiologist", "Dermatologist", "Gastroenterologist", "Hematologist", "Internal Medicine Physician", "Nephrologist", "Neurologist", "Neurosurgeon", "Obstetrician", "Gynecologist", "Nurse-Midwifery", "Ophthalmologist", "Maxillofacial Surgeon", "Orthopaedic Surgeon", "Otolaryngologist", "Pathologist", "Pediatrician", "Psychiatrist", "Urologist" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(210, 100, 140, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "low", "normal", "emergency" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(210, 230, 140, 30);

        jLabel1.setText("Doctor ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 170, 80, 30);

        jLabel2.setText("Choose Specialist");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 110, 130, 30);

        jLabel3.setText("Priority");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 230, 70, 30);

        jLabel4.setText("Patient ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 40, 60, 30);

        jButton1.setText("Add Appointment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 300, 140, 30);

        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(210, 170, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 60, 510, 410);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("Request Appointment");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(150, 10, 210, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 510, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
     
     
       String cat=jComboBox2.getSelectedItem().toString();
       
     try{
         Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/telemedicine", "root", "");
            Statement state = cn.createStatement();
            //String sql="select ip,date,time as AccessTime,SECOND(time) as seconds from iplist ";
            String sql="select distinct did from consultant where category='"+cat+"'";
            
         ResultSet rs=state.executeQuery(sql);
 while(rs.next()){
    jComboBox5.addItem(rs.getString(1));
 }
          
    }   catch (ClassNotFoundException ex) {
            Logger.getLogger(AddAppoint.class.getName()).log(Level.SEVERE, null, ex);
        }
    catch(SQLException e)
    {
        System.out.println(e);
    }
     
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String pid=jComboBox1.getSelectedItem().toString();
       
 
      String cdid=jComboBox5.getSelectedItem().toString();
      String pri=jComboBox3.getSelectedItem().toString();
        try{
    Class.forName("com.mysql.jdbc.Driver");
        
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/telemedicine", "root", "");
          Statement st = con.createStatement();
String qry="insert into appointments values(null,'"+pid+"','"+cdid+"','"+pri+"')";
st.execute(qry);
 JOptionPane.showMessageDialog(null, "Appointment Requested");


}

catch(Exception e){System.out.println(e);}
 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAppoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAppoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAppoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAppoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAppoint().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
