
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Reports extends javax.swing.JFrame {


public static File file;
public static FileInputStream fis ;
 public static    long len;
    public Reports() {
        initComponents();
        
       SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy"); 
    String fd = formatter.format(new Date()); 
   
    jTextField1.setText(fd);
 
        try{
            Class.forName("com.mysql.jdbc.Driver");
        
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/telemedicine", "root", "");
          Statement st = con.createStatement();
          String qry="select pid from lpatients;";
      ResultSet rs= st.executeQuery(qry);
      jComboBox1.removeAll();
      while(rs.next()){
          
      jComboBox1.addItem(rs.getString(1));
      }
      rs.close();
      st.close();
         
        
        }
        catch(Exception e){
        System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(560, 430));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Report Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 520, 80);

        jPanel2.setBackground(new java.awt.Color(204, 234, 234));
        jPanel2.setLayout(null);

        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(130, 20, 170, 30);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(130, 80, 350, 30);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(130, 130, 350, 30);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(130, 180, 270, 30);

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(410, 180, 73, 30);

        jLabel1.setText("Report Date");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 80, 90, 30);

        jLabel2.setText("Report Detail");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 134, 80, 20);

        jLabel3.setText("Report File");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 184, 70, 20);

        jLabel4.setText("patient ID");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 20, 110, 30);

        jButton2.setText("Add Report Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(170, 230, 130, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 100, 520, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       file = jFileChooser1.getSelectedFile();
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == jFileChooser1.APPROVE_OPTION) {
            jTextField3.setText(jFileChooser1.getSelectedFile().getAbsolutePath());
        }
        File f=new File(jTextField3.getText());
         try {
            fis = new FileInputStream(f);
            
           len=f.length(); 
        } catch (Exception ex) {
           System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

   String pid=jComboBox1.getSelectedItem().toString();
      String rdate=jTextField1.getText();
      String rdetail=jTextField2.getText();
     
     
        try{
    Class.forName("com.mysql.jdbc.Driver");
        
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/telemedicine", "root", "");
          Statement st = con.createStatement();
          String qry="insert into lpatientreports value('"+pid+"','"+rdate+"','"+rdetail+"','"+fis +"')";
      // System.out.println(qry);
          st.execute(qry);
         JOptionPane.showMessageDialog(null, "patient Report Details Added");
         this.setVisible(false);
         
          }

catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
