
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Treat extends javax.swing.JFrame {

public static File file;
public static FileInputStream fis ;
 public static    long len;
    public Treat() {
        initComponents();
           SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy"); 
            SimpleDateFormat formatter2 = new SimpleDateFormat("hh:mm:ss a"); 
    String fd = formatter.format(new Date()); 
    String fd2=formatter2.format(new Date());
    jTextField4.setText(fd);
    jTextField5.setText(fd2);
        try{
            Class.forName("com.mysql.jdbc.Driver");
        
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/telemedicine", "root", "");
          Statement st = con.createStatement();
          String qry="select pid from lpatients;";
      ResultSet rs= st.executeQuery(qry);
      jComboBox1.removeAll();
      while(rs.next()){
          
      jComboBox1.addItem(rs.getString(1));
      }
      rs.close();
      st.close();
         
        
        }
        catch(Exception e){
        System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 750));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(230, 30, 100, 30);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(230, 80, 150, 30);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(230, 130, 150, 30);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(230, 180, 150, 30);

        jLabel1.setText("heartbeat Rate");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 380, 100, 30);

        jLabel2.setText("Symptoms");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 130, 60, 30);

        jLabel3.setText("Date of Admit");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 180, 80, 40);

        jLabel4.setText("Patient ID");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 30, 120, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(230, 430, 220, 50);

        jLabel5.setText("Disease");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 80, 80, 30);

        jLabel6.setText("Priority");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(70, 510, 70, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "low", "normal", "emergency" }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(240, 510, 110, 30);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(230, 230, 150, 30);

        jLabel7.setText("Date Of treatment");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(70, 220, 100, 50);

        jLabel8.setText("Time Of Treatment");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, 280, 110, 30);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(230, 280, 150, 30);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(230, 330, 150, 30);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(230, 380, 150, 30);

        jLabel10.setText("Pulse Rate");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(70, 330, 100, 30);

        jButton1.setText("Add Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(130, 570, 110, 30);

        jLabel11.setText("Treatment Given");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(70, 430, 100, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 60, 490, 630);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Treatment Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 10, 490, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
       
       
        String pid=jComboBox1.getSelectedItem().toString();
      String dis=jTextField1.getText();
      String sym=jTextField2.getText();
      String dur=jTextField3.getText();
      String date=jTextField4.getText();
      String time=jTextField5.getText();
      String pulse=jTextField6.getText();
      String heart=jTextField7.getText();
      String treat=jTextArea1.getText();
      String pri=jComboBox2.getSelectedItem().toString();
        try{
    Class.forName("com.mysql.jdbc.Driver");
        
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/telemedicine", "root", "");
          Statement st = con.createStatement();
          String qry="insert into lpatienttreat value('"+pid+"','"+dis+"','"+sym+"','"+dur+"','"+date+"','"+time+"','"+pulse+"','"+heart+"','"+treat+"','"+pri+"')";
       //System.out.println(qry);
          st.execute(qry);
         JOptionPane.showMessageDialog(null, "patient Treatment Details Added");
         this.setVisible(false);
         
          }

catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Treat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Treat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Treat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Treat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Treat().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
